### ISSUE TITLE
view试图层级实现疑问？所有子试图完全展开垂直布局，然后外面包一个scrollview？web全部展开一下子占很大内存，评论table也没有了复用，这个思路有问题啊，老弟！

### ISSUE THREAD

**Issue by wulinfeng198810** [dequan1331/HybridPageKit#13]
你这个

**Comment by wulinfeng198810** [comment]
view试图层级实现思路有问题！

**Comment by dequan1331** [comment]
所有的webview和tableview都是和屏幕一样大，都有复用的
相关的实现思路就是整体框架的核心技术之一：异构滚动视图的协同滚动
具体的思路可以参考：https://dequan1331.github.io/hybrid-page-kit.html中《WebView内容区与Native扩展区的衔接》这一部分哈～
