### ISSUE TITLE
native view渲染方式

### ISSUE THREAD

**Issue by niuxinghua** [dequan1331/HybridPageKit#14]
html计算实际站位的native view的过程在js里面是不是很消耗性能，能不能通过类似yoga之类的布局引擎去优化？

**Comment by niuxinghua** [comment]
通过yoga做一个类似flex box布局的计算 把位置异步计算出来 再去添加native view到站位的位置。应该比js算要好

**Comment by dequan1331** [comment]
对于目前的场景来讲，我们只是在页面加载之后，取一次Dom节点的信息，触发的时机比较少，只有加载成功+页面有变化（比如调整字体大小）。

以我的理解哈，yoga是解析flex-box布局，高效的计算位置。感觉在这个场景下有些大才小用了，还要引入相应的库以及遵循flex-box的布局等，并不是很划算。
