### ISSUE TITLE
请问新版本修改了些什么东西呀？

### ISSUE THREAD

**Issue by Laixg** [dequan1331/HybridPageKit#15]

**Comment by dequan1331** [comment]
整体的框架设计思路没有变化

**Comment by dequan1331** [comment]
最主要的改变，是之前有开发者反馈对于Controller层级，是不是也可以使用协议的方式，而不是继承。所以在新版本中，整个复杂底层页的MVC都是通过协议的方式实现，对源代码侵入更小，集成更方便。

**Comment by dequan1331** [comment]
其余对还有一些bug修复、以及增加扩展对小功能等。

**Comment by Laixg** [comment]
谢谢回答，我这边用新版本试一下。能否把评论模块写一个假数据model做一个demo，之前的版本评论会出问题。

**Comment by Laixg** [comment]
评论接口是异步的，如果进来的时候请求失败就一直看不到评论。接口重试在什么地方调用比较好呢？
