### ISSUE TITLE
正文内容小于一屏 会有留白出现

### ISSUE THREAD

**Issue by Laixg** [dequan1331/HybridPageKit#16]

**Comment by dequan1331** [comment]
fix - 49da333, 小于一屏幕的时候加入了js检测

**Comment by wangweihu** [comment]
小于一屏幕的时候，获取高度不稳定，时好时坏的

**Comment by dequan1331** [comment]
@wangweihu 是用Demo么，还是自己集成的代码，方便提供下代码和场景么？

**Comment by wangweihu** [comment]
昨天验证了和客户端无关，是H5那边 style样式 height:100%  高度塌陷  造成的

**Comment by dequan1331** [comment]
那我close了哈
