### ISSUE TITLE
UIView上面加载WebView

### ISSUE THREAD

**Issue by ismilesky** [dequan1331/HybridPageKit#17]
在UIView上面加载WebView时，native + webView， HPKPageHandler 需要怎么初始化， 在ViewController是```
- (void)configWithViewController:(__kindof UIViewController *)viewController
           componentsControllers:(NSArray<HPKController *> *)componentsControllers;
```

**Comment by ismilesky** [comment]
还有一个问题，Demo实例中当只添加一个TitleController时， NestingWebViewController只显示一屏，containerScrollView无法滚动， containerScrollView的contentSize不对，退出再次进入就可以了，请问是什么问题

**Comment by Laixg** [comment]
我也遇到了这个问题

**Comment by Laixg** [comment]
我也遇到了这个问题 你有解决吗？

**Comment by ismilesky** [comment]
试了个临时方案，能行，但可能滚动的时候会不断计算会影响性能, 滚动的时候调用 relayoutWithComponentChange

**Comment by ismilesky** [comment]
怎么适配横竖屏切换， 该怎样处理？ 求教

**Comment by dequan1331** [comment]
"Demo实例中当只添加一个TitleController时， NestingWebViewController只显示一屏 "
这个问题已修复 - commit b395abd

**Comment by dequan1331** [comment]
“怎么适配横竖屏切换， 该怎样处理？ 求教”  
这个暂时没有适配的计划，目前主流的App也没有横屏的场景，特殊业务逻辑需要二次开发了
