### ISSUE TITLE
想用 UIWebview 有什么替换方案吗

### ISSUE THREAD

**Issue by karosLi** [dequan1331/HybridPageKit#19]

**Comment by dequan1331** [comment]
uiwebview 已经被标记为deprecated了 请问为什么要使用呢，目前大部分的功能，都已经有较为成熟的替代方案了

**Comment by karosLi** [comment]
> uiwebview 已经被标记为deprecated了 请问为什么要使用呢，目前大部分的功能，都已经有较为成熟的替代方案了

因为我们有离线包。POST Body 会被 WK 丢失掉。

**Comment by dequan1331** [comment]
离线包相关的逻辑，可以结合localServer的方案解决，目前大部分的成熟方案也都是这么做的，可以考虑下

**Comment by karosLi** [comment]
> 离线包相关的逻辑，可以结合localServer的方案解决，目前大部分的成熟方案也都是这么做的，可以考虑下

恩，大概了解了下，会有 CocoaHTTPServer 和 GCDWebServer 两个方案，我看你之前的写的文章里说是使用 GCDWebServer 的，但是这个方案好像不支持 https的。
