### ISSUE TITLE
点击图片事件如何回调

### ISSUE THREAD

**Issue by ChirsJoe** [dequan1331/HybridPageKit#24]
想做预览图片，点击图片如何回调到当前的ViewController中呢？

**Comment by dequan1331** [comment]
如果使用了HybridPageKit中的webComponentDomClass及webComponentIndexKey来替换全部的web标签为Native的话，点击图片的事件直接加到ImageView上即可。可以设置对应的特殊ImageView类，或者在HPKControllerProtocol中的willAppear中直接添加，在willDisappear中移除。
如果没有使用，希望是在<img>标签中响应，就需要书写JS代码并且和Native进行通信了，可以使用WKWebView自带的或开源第三方框架进行通信。JS获取图片信息以及位置，传递给Native做动画和展示。
