### ISSUE TITLE
HybridPageKit  是否实现了本地HTTP代理server

### ISSUE THREAD

**Issue by wangweihu** [dequan1331/HybridPageKit#26]
除了NSURLProtocol拦截H5请求外，HTTP代理server也是一个方法，这个有实现吗

**Comment by dequan1331** [comment]
这个是需要在业务层实现的，一般来说使用GCDWebServer即可，在HybridPageKit没有集成

**Comment by karosLi** [comment]
![image](https://user-images.githubusercontent.com/6810941/61443114-6f9ad380-a97b-11e9-85d5-f48abfd149f7.png)

这块想请教下，WKWebView 是怎么做到重定向请求到 Local Server 的呢，因为如果是通过URLProtocol去重定向请求，实际上是丢失http ajax body，那这里是怎么做到资源请求都重定向到 Local Server 上的呢？

**Comment by LJW008** [comment]
同文，朱老师
