### ISSUE TITLE
无导航，iOS11 有问题

### ISSUE THREAD

**Issue by Suzhibin** [dequan1331/HybridPageKit#27]
大神您好，页面无导航，页面最上面有空白。
在HPKAbstractViewController.m
_containerScrollView 的高度 把-64 去掉 并写下面代码
  if (@available(iOS 11.0,*))  {
            _containerScrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }else{
            self.automaticallyAdjustsScrollViewInsets=NO;
        }
布局就乱了 ，运营推广区和扩展阅读区跑到评论下面去了。

**Comment by dequan1331** [comment]
框架有了一次较大的升级，新的代码已经全部面向协议实现，无需继承ViewController了，所以相应的代码都已经删除了。感兴趣的话可以使用下新代码。
