### ISSUE TITLE
请问如何注入js方法到webview

### ISSUE THREAD

**Issue by MarsLeo** [dequan1331/HybridPageKit#39]
请问如何注入js方法到webview，在初始化HPKWebView的时候没有添加UserContentController的地方，希望能指导一下。谢谢

**Comment by dequan1331** [comment]
可以创建一个自己的 WebView 继承自 HPKWebView。重写对应的initWithFrame方法。这样可以实现自定义的逻辑，同时也不会影响框架内部的逻辑。
