### ISSUE TITLE
懒加载图片的时候注入加载图片的js

### ISSUE THREAD

**Issue by JJ-Abel** [dequan1331/HybridPageKit#40]
[self.componentHandler.webView evaluateJavaScript:@"loadImages()" completionHandler:^(id _Nullable data, NSError * _Nullable error) {
        if (error) {
            NSLog(@"错误:------>%@", error);
        }
}];

打印：
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=22, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: $, WKJavaScriptExceptionColumnNumber=16, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred}

**Comment by dequan1331** [comment]
看样子是 loadImages() 里面的 JS 执行错误。 loadImages() 这个不是框架实现的吧？应该是你的业务逻辑代码？
