### ISSUE TITLE
你好 有关wkwebView设置cookies问题 

### ISSUE THREAD

**Issue by MoShenGuo** [dequan1331/HybridPageKit#43]
你好 有关wkwebView设置cookies问题你是怎么处理的?怎么解决的呢?谢谢

**Comment by dequan1331** [comment]
在WKWebView中不会自动带上cookie。对于一般的业务场景，比如注入登录态，就需要业务侧主动将cookies注入到webview中。在框架中HPKWebView也提供了相对简单的Javascript方法封装，setCookieWithName & deleteCookiesWithName & getAllCustomCookiesName & deleteAllCustomCookies。我们可以将存储在NSHTTPCookieStorage中的cookies按照domain的关系取出然后注入到webview中。对于请求我们可以在对应的header中手动设置。当然对于iOS11+，系统也提供了WKHTTPCookieStore这个类，但是目前常用的App都需要支持更低的版本。
